config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=33566 &distance=20&API_KEY=62A8ECF3-0D29-41BE-997F-D31E4A91BC57'
    @uri = URI(@url)

    begin
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
    rescue StandardError => e
      puts "Error occurred: #{e.message}"
      @output = []
    end
   
    
    #Check for empty results array
    if @output.empty?
      @final_output = 'Error'
    elsif !@output
      @final_output = 'Error'
    else 
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color="error"
    elsif @final_output.to_i <= 50
      @api_color="green"
      @api_description = "The air quality in your area is good"
    elsif @final_output.to_i >= 51 && @final_output <= 100
      @api_color="yellow"
      @api_description = "The air quality in your area is between 51 and 100, which means it is acceptable, but some pollutants may be a moderate health concern for sensitive people" 
    elsif @final_output.to_i >= 101 && @final_output <= 150
      @api_color="orange" 
      @api_description = "The air quality in your area is between 101 and 150, which means it is unhealthy for sensitive groups. People with lung disease, older adults, and children are at greater risk from exposure to ozone and particulates in the air" 
    elsif @final_output.to_i >= 151 && @final_output <= 200
      @api_color="red" 
      @api_description = "The air quality in your area is between 151 and 200, which means it is unhealthy and everyone may experience more serious health effects"
    elsif @final_output.to_i >= 201 && @final_output <= 300
      @api_color="purple"
      @api_description = "The air quality in your area is between 201 and 300, which means it is very unhealthy and everyone may experience health effects"
    elsif @final_output.to_i >= 301 && @final_output <= 500
      @api_color="maroon"  
      @api_description = "The air quality in your area is between 301 and 500, which means it is hazardous and the entire population is likely to be affected"
    end 
  end
 
  def zipcode
    @zip_query = params[:zipcode]  
     
    if params[:zipcode].blank?
        flash[:error] = "Hey, you forgot to enter a zip code"
        redirect_to root_path
    elsif params[:zipcode]
    #do API stuff:
    require 'net/http'
    require 'json'
    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query + '&distance=20&API_KEY=62A8ECF3-0D29-41BE-997F-D31E4A91BC57'
    @uri = URI(@url)

    begin
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
    rescue StandardError => e
      puts "Error occurred: #{e.message}"
      @output = []
    end
   
    
    #Check for empty results array
    if @output.empty?
      @final_output = 'Error'
    elsif !@output
      @final_output = 'Error'
    else 
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color="error"
    elsif @final_output.to_i <= 50
      @api_color="green"
      @api_description = "The air quality in your area is good"
    elsif @final_output.to_i >= 51 && @final_output <= 100
      @api_color="yellow"
      @api_description = "The air quality in your area is between 51 and 100, which means it is acceptable, but some pollutants may be a moderate health concern for sensitive people" 
    elsif @final_output.to_i >= 101 && @final_output <= 150
      @api_color="orange" 
      @api_description = "The air quality in your area is between 101 and 150, which means it is unhealthy for sensitive groups. People with lung disease, older adults, and children are at greater risk from exposure to ozone and particulates in the air" 
    elsif @final_output.to_i >= 151 && @final_output <= 200
      @api_color="red" 
      @api_description = "The air quality in your area is between 151 and 200, which means it is unhealthy and everyone may experience more serious health effects"
    elsif @final_output.to_i >= 201 && @final_output <= 300
      @api_color="purple"
      @api_description = "The air quality in your area is between 201 and 300, which means it is very unhealthy and everyone may experience health effects"
    elsif @final_output.to_i >= 301 && @final_output <= 500
      @api_color="maroon"  
      @api_description = "The air quality in your area is between 301 and 500, which means it is hazardous and the entire population is likely to be affected"
    end 




    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/zipcode_helper.rb
module ZipcodeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "My Ozone", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
      </ul>

      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="d-flex"> 
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zip Code", class: "form-control me-2", data: {turbo:"false"} %>
        <%= submit_tag 'Search', class: "btn btn-outline-light", data: {turbo:"false"} %>

       </div> 

       <% end %>








    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container <%= @api_color%> text-white flex rounded p-5">

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>


    <h1 class="display-4">My Air Quality App</h1>
    <h3>AQI: <%= @final_output %></h3>
    <p class="lead p-1">This is the current Ozone air quality readout for my neighborhood</p>
    <hr class="my-4 p-1">
    <p><%= @api_description %></p>
    <p>Reload to update the reading</p>    
    <br><br>
</div>
</div>

<br>

app/views/home/zipcode.html.erb
<div class="container <%= @api_color%> text-white flex rounded p-5">

    <h1 class="display-4">My Air Quality App</h1>
    <h3>AQI: <%= @final_output %></h3>
    <p class="lead p-1">Zip Code: <%= @zip_query %></p>
    <hr class="my-4 p-1">
    <p><%= @api_description %></p>
    <p>Reload to update the reading</p>    
    <br><br>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
    <br>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/zipcode/home.html.erb
<h1>Zipcode#home</h1>
<p>Find me in app/views/zipcode/home.html.erb</p>